/**
 * AirAsia Local Sample Flight Data
 * Fully offline, frontend-only demonstration dataset.
 * Contains 40+ realistic sample flights across major AirAsia domestic and international routes.
 * No external APIs, databases, or backend services required.
 */

window.AIRASIA_FLIGHTS_DATA = [
  // DAC <-> KUL (Dhaka to Kuala Lumpur)
  {
    id: "FL-001",
    flightNumber: "AK-512",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "KUL",
    destinationCity: "Kuala Lumpur",
    destinationAirport: "Kuala Lumpur International Airport (Terminal 2)",
    daysAhead: 1,
    departureTime: "01:25",
    arrivalTime: "07:15",
    duration: "3h 50m",
    durationMinutes: 230,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 18,
    baseFareBDT: 21500,
    taxBDT: 3000,
    priceBDT: 24500,
    amenities: ["Carry-on 7kg", "USB Charging", "In-flight Purchase"]
  },
  {
    id: "FL-002",
    flightNumber: "AK-514",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "KUL",
    destinationCity: "Kuala Lumpur",
    destinationAirport: "Kuala Lumpur International Airport (Terminal 2)",
    daysAhead: 1,
    departureTime: "12:40",
    arrivalTime: "18:35",
    duration: "3h 55m",
    durationMinutes: 235,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A321neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 32,
    baseFareBDT: 23200,
    taxBDT: 3100,
    priceBDT: 26300,
    amenities: ["Carry-on 7kg", "Hot Meal Pre-order", "Comfort Seats"]
  },
  {
    id: "FL-003",
    flightNumber: "D7-182",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "KUL",
    destinationCity: "Kuala Lumpur",
    destinationAirport: "Kuala Lumpur International Airport (Terminal 2)",
    daysAhead: 1,
    departureTime: "22:15",
    arrivalTime: "04:10",
    duration: "3h 55m",
    durationMinutes: 235,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A330-300",
    cabinClass: "Premium Flatbed",
    baggageAllowance: "40 kg check-in + 7 kg cabin",
    availableSeats: 8,
    baseFareBDT: 54000,
    taxBDT: 4500,
    priceBDT: 58500,
    amenities: ["Flatbed Seat", "40kg Baggage", "Complimentary Meal", "Priority Boarding"]
  },
  {
    id: "FL-004",
    flightNumber: "AK-516",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "KUL",
    destinationCity: "Kuala Lumpur",
    destinationAirport: "Kuala Lumpur International Airport (Terminal 2)",
    daysAhead: 2,
    departureTime: "08:15",
    arrivalTime: "14:10",
    duration: "3h 55m",
    durationMinutes: 235,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 24,
    baseFareBDT: 20500,
    taxBDT: 3000,
    priceBDT: 23500,
    amenities: ["Carry-on 7kg", "Santan Café"]
  },
  {
    id: "FL-005",
    flightNumber: "AK-518",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "KUL",
    destinationCity: "Kuala Lumpur",
    destinationAirport: "Kuala Lumpur International Airport (Terminal 2)",
    daysAhead: 3,
    departureTime: "16:20",
    arrivalTime: "22:15",
    duration: "3h 55m",
    durationMinutes: 235,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A321neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 14,
    baseFareBDT: 22000,
    taxBDT: 3000,
    priceBDT: 25000,
    amenities: ["Carry-on 7kg", "Extra Legroom Options"]
  },

  // KUL <-> DAC (Kuala Lumpur to Dhaka - Returns & Reverse)
  {
    id: "FL-006",
    flightNumber: "AK-513",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "DAC",
    destinationCity: "Dhaka",
    destinationAirport: "Hazrat Shahjalal Intl Airport",
    daysAhead: 4,
    departureTime: "09:30",
    arrivalTime: "11:20",
    duration: "3h 50m",
    durationMinutes: 230,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 26,
    baseFareBDT: 21000,
    taxBDT: 3200,
    priceBDT: 24200,
    amenities: ["Carry-on 7kg", "Santan Meals"]
  },
  {
    id: "FL-007",
    flightNumber: "AK-515",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "DAC",
    destinationCity: "Dhaka",
    destinationAirport: "Hazrat Shahjalal Intl Airport",
    daysAhead: 4,
    departureTime: "19:45",
    arrivalTime: "21:35",
    duration: "3h 50m",
    durationMinutes: 230,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A321neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 15,
    baseFareBDT: 22500,
    taxBDT: 3200,
    priceBDT: 25700,
    amenities: ["Carry-on 7kg", "Power Outlets"]
  },
  {
    id: "FL-008",
    flightNumber: "D7-183",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "DAC",
    destinationCity: "Dhaka",
    destinationAirport: "Hazrat Shahjalal Intl Airport",
    daysAhead: 5,
    departureTime: "17:10",
    arrivalTime: "19:05",
    duration: "3h 55m",
    durationMinutes: 235,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A330-300",
    cabinClass: "Premium Flatbed",
    baggageAllowance: "40 kg check-in + 7 kg cabin",
    availableSeats: 6,
    baseFareBDT: 55000,
    taxBDT: 4500,
    priceBDT: 59500,
    amenities: ["Flatbed Seat", "40kg Baggage", "Complimentary Meal", "Lounge Access"]
  },

  // DAC <-> BKK (Dhaka to Bangkok)
  {
    id: "FL-009",
    flightNumber: "FD-181",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "BKK",
    destinationCity: "Bangkok",
    destinationAirport: "Don Mueang International Airport (DMK)",
    daysAhead: 1,
    departureTime: "02:10",
    arrivalTime: "05:40",
    duration: "2h 30m",
    durationMinutes: 150,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 22,
    baseFareBDT: 16500,
    taxBDT: 2700,
    priceBDT: 19200,
    amenities: ["Carry-on 7kg", "Thai Street Food Menu"]
  },
  {
    id: "FL-010",
    flightNumber: "FD-183",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "BKK",
    destinationCity: "Bangkok",
    destinationAirport: "Don Mueang International Airport (DMK)",
    daysAhead: 1,
    departureTime: "15:45",
    arrivalTime: "19:15",
    duration: "2h 30m",
    durationMinutes: 150,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A321neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 19,
    baseFareBDT: 17800,
    taxBDT: 2700,
    priceBDT: 20500,
    amenities: ["Carry-on 7kg", "Hot Seats Available"]
  },
  {
    id: "FL-011",
    flightNumber: "FD-182",
    origin: "BKK",
    originCity: "Bangkok",
    originAirport: "Don Mueang International Airport (DMK)",
    destination: "DAC",
    destinationCity: "Dhaka",
    destinationAirport: "Hazrat Shahjalal Intl Airport",
    daysAhead: 4,
    departureTime: "23:25",
    arrivalTime: "01:00",
    duration: "2h 35m",
    durationMinutes: 155,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 28,
    baseFareBDT: 16000,
    taxBDT: 2800,
    priceBDT: 18800,
    amenities: ["Carry-on 7kg", "Duty Free Shopping"]
  },

  // DAC <-> SIN (Dhaka to Singapore via KUL or Direct)
  {
    id: "FL-012",
    flightNumber: "AK-512 / AK-705",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "SIN",
    destinationCity: "Singapore",
    destinationAirport: "Singapore Changi Airport",
    daysAhead: 1,
    departureTime: "01:25",
    arrivalTime: "10:15",
    duration: "6h 50m",
    durationMinutes: 410,
    stops: 1,
    stopsText: "1 Stop (KUL 1h 45m)",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 14,
    baseFareBDT: 25000,
    taxBDT: 3800,
    priceBDT: 28800,
    amenities: ["Carry-on 7kg", "Fly-Thru Luggage Transfer"]
  },
  {
    id: "FL-013",
    flightNumber: "AK-514 / AK-711",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "SIN",
    destinationCity: "Singapore",
    destinationAirport: "Singapore Changi Airport",
    daysAhead: 2,
    departureTime: "12:40",
    arrivalTime: "21:30",
    duration: "6h 50m",
    durationMinutes: 410,
    stops: 1,
    stopsText: "1 Stop (KUL 1h 50m)",
    aircraft: "Airbus A321neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 20,
    baseFareBDT: 26500,
    taxBDT: 3800,
    priceBDT: 30300,
    amenities: ["Carry-on 7kg", "Fly-Thru Transfer", "Hot Meals"]
  },
  {
    id: "FL-014",
    flightNumber: "AK-706 / AK-515",
    origin: "SIN",
    originCity: "Singapore",
    originAirport: "Singapore Changi Airport",
    destination: "DAC",
    destinationCity: "Dhaka",
    destinationAirport: "Hazrat Shahjalal Intl Airport",
    daysAhead: 5,
    departureTime: "16:20",
    arrivalTime: "21:35",
    duration: "7h 15m",
    durationMinutes: 435,
    stops: 1,
    stopsText: "1 Stop (KUL 2h 10m)",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 16,
    baseFareBDT: 25500,
    taxBDT: 3900,
    priceBDT: 29400,
    amenities: ["Carry-on 7kg", "Changi Terminal Transfer"]
  },

  // KUL <-> SIN (Kuala Lumpur to Singapore)
  {
    id: "FL-015",
    flightNumber: "AK-701",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "SIN",
    destinationCity: "Singapore",
    destinationAirport: "Singapore Changi Airport",
    daysAhead: 1,
    departureTime: "07:05",
    arrivalTime: "08:15",
    duration: "1h 10m",
    durationMinutes: 70,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 45,
    baseFareBDT: 4800,
    taxBDT: 1500,
    priceBDT: 6300,
    amenities: ["Carry-on 7kg", "Express Shuttle Route"]
  },
  {
    id: "FL-016",
    flightNumber: "AK-705",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "SIN",
    destinationCity: "Singapore",
    destinationAirport: "Singapore Changi Airport",
    daysAhead: 1,
    departureTime: "14:15",
    arrivalTime: "15:25",
    duration: "1h 10m",
    durationMinutes: 70,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 30,
    baseFareBDT: 5200,
    taxBDT: 1500,
    priceBDT: 6700,
    amenities: ["Carry-on 7kg", "Hot Snack Options"]
  },
  {
    id: "FL-017",
    flightNumber: "AK-717",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "SIN",
    destinationCity: "Singapore",
    destinationAirport: "Singapore Changi Airport",
    daysAhead: 2,
    departureTime: "20:30",
    arrivalTime: "21:40",
    duration: "1h 10m",
    durationMinutes: 70,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 22,
    baseFareBDT: 4500,
    taxBDT: 1500,
    priceBDT: 6000,
    amenities: ["Carry-on 7kg"]
  },
  {
    id: "FL-018",
    flightNumber: "AK-702",
    origin: "SIN",
    originCity: "Singapore",
    originAirport: "Singapore Changi Airport",
    destination: "KUL",
    destinationCity: "Kuala Lumpur",
    destinationAirport: "Kuala Lumpur International Airport (Terminal 2)",
    daysAhead: 3,
    departureTime: "09:00",
    arrivalTime: "10:10",
    duration: "1h 10m",
    durationMinutes: 70,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 38,
    baseFareBDT: 4900,
    taxBDT: 1600,
    priceBDT: 6500,
    amenities: ["Carry-on 7kg"]
  },

  // KUL <-> DPS (Kuala Lumpur to Bali)
  {
    id: "FL-019",
    flightNumber: "QZ-551",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "DPS",
    destinationCity: "Bali",
    destinationAirport: "Ngurah Rai International Airport",
    daysAhead: 1,
    departureTime: "09:20",
    arrivalTime: "12:25",
    duration: "3h 05m",
    durationMinutes: 185,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 16,
    baseFareBDT: 13500,
    taxBDT: 2400,
    priceBDT: 15900,
    amenities: ["Carry-on 7kg", "Tropical Refreshments"]
  },
  {
    id: "FL-020",
    flightNumber: "D7-798",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "DPS",
    destinationCity: "Bali",
    destinationAirport: "Ngurah Rai International Airport",
    daysAhead: 2,
    departureTime: "15:40",
    arrivalTime: "18:45",
    duration: "3h 05m",
    durationMinutes: 185,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A330-300",
    cabinClass: "Premium Flatbed",
    baggageAllowance: "40 kg check-in + 7 kg cabin",
    availableSeats: 4,
    baseFareBDT: 38000,
    taxBDT: 3500,
    priceBDT: 41500,
    amenities: ["Flatbed Comfort", "40kg Baggage", "Complimentary Meal", "Fast Track"]
  },
  {
    id: "FL-021",
    flightNumber: "QZ-552",
    origin: "DPS",
    originCity: "Bali",
    originAirport: "Ngurah Rai International Airport",
    destination: "KUL",
    destinationCity: "Kuala Lumpur",
    destinationAirport: "Kuala Lumpur International Airport (Terminal 2)",
    daysAhead: 4,
    departureTime: "13:10",
    arrivalTime: "16:15",
    duration: "3h 05m",
    durationMinutes: 185,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 21,
    baseFareBDT: 14200,
    taxBDT: 2400,
    priceBDT: 16600,
    amenities: ["Carry-on 7kg", "Santan Nasi Lemak"]
  },

  // KUL <-> BKK (Kuala Lumpur to Bangkok)
  {
    id: "FL-022",
    flightNumber: "FD-3101",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "BKK",
    destinationCity: "Bangkok",
    destinationAirport: "Don Mueang International Airport (DMK)",
    daysAhead: 1,
    departureTime: "06:45",
    arrivalTime: "08:00",
    duration: "2h 15m",
    durationMinutes: 135,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 35,
    baseFareBDT: 8500,
    taxBDT: 1900,
    priceBDT: 10400,
    amenities: ["Carry-on 7kg", "Morning Coffee Service"]
  },
  {
    id: "FL-023",
    flightNumber: "AK-882",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "BKK",
    destinationCity: "Bangkok",
    destinationAirport: "Don Mueang International Airport (DMK)",
    daysAhead: 1,
    departureTime: "11:55",
    arrivalTime: "13:10",
    duration: "2h 15m",
    durationMinutes: 135,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 27,
    baseFareBDT: 9200,
    taxBDT: 1900,
    priceBDT: 11100,
    amenities: ["Carry-on 7kg", "Hot Meals Available"]
  },
  {
    id: "FL-024",
    flightNumber: "AK-886",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "BKK",
    destinationCity: "Bangkok",
    destinationAirport: "Don Mueang International Airport (DMK)",
    daysAhead: 2,
    departureTime: "18:40",
    arrivalTime: "19:55",
    duration: "2h 15m",
    durationMinutes: 135,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A321neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 19,
    baseFareBDT: 9800,
    taxBDT: 1900,
    priceBDT: 11700,
    amenities: ["Carry-on 7kg", "Quiet Zone Seating"]
  },

  // DAC <-> PEN (Dhaka to Penang via KUL)
  {
    id: "FL-025",
    flightNumber: "AK-512 / AK-6112",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "PEN",
    destinationCity: "Penang",
    destinationAirport: "Penang International Airport",
    daysAhead: 1,
    departureTime: "01:25",
    arrivalTime: "09:50",
    duration: "6h 25m",
    durationMinutes: 385,
    stops: 1,
    stopsText: "1 Stop (KUL 1h 35m)",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 12,
    baseFareBDT: 23800,
    taxBDT: 3400,
    priceBDT: 27200,
    amenities: ["Carry-on 7kg", "Fly-Thru Connection"]
  },
  {
    id: "FL-026",
    flightNumber: "AK-6113 / AK-515",
    origin: "PEN",
    originCity: "Penang",
    originAirport: "Penang International Airport",
    destination: "DAC",
    destinationCity: "Dhaka",
    destinationAirport: "Hazrat Shahjalal Intl Airport",
    daysAhead: 4,
    departureTime: "16:40",
    arrivalTime: "21:35",
    duration: "6h 55m",
    durationMinutes: 415,
    stops: 1,
    stopsText: "1 Stop (KUL 2h 05m)",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 18,
    baseFareBDT: 24200,
    taxBDT: 3400,
    priceBDT: 27600,
    amenities: ["Carry-on 7kg", "Fly-Thru Connection"]
  },

  // KUL <-> HKT (Kuala Lumpur to Phuket)
  {
    id: "FL-027",
    flightNumber: "AK-824",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "HKT",
    destinationCity: "Phuket",
    destinationAirport: "Phuket International Airport",
    daysAhead: 1,
    departureTime: "10:15",
    arrivalTime: "10:40",
    duration: "1h 25m",
    durationMinutes: 85,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 29,
    baseFareBDT: 7200,
    taxBDT: 1700,
    priceBDT: 8900,
    amenities: ["Carry-on 7kg", "Beach Holiday Route"]
  },
  {
    id: "FL-028",
    flightNumber: "AK-828",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "HKT",
    destinationCity: "Phuket",
    destinationAirport: "Phuket International Airport",
    daysAhead: 2,
    departureTime: "17:50",
    arrivalTime: "18:15",
    duration: "1h 25m",
    durationMinutes: 85,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 25,
    baseFareBDT: 7800,
    taxBDT: 1700,
    priceBDT: 9500,
    amenities: ["Carry-on 7kg"]
  },

  // KUL <-> TYO/HND (Kuala Lumpur to Tokyo Haneda)
  {
    id: "FL-029",
    flightNumber: "D7-522",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "TYO",
    destinationCity: "Tokyo",
    destinationAirport: "Haneda Airport (HND)",
    daysAhead: 2,
    departureTime: "14:30",
    arrivalTime: "22:30",
    duration: "7h 00m",
    durationMinutes: 420,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A330-300",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 40,
    baseFareBDT: 32000,
    taxBDT: 4800,
    priceBDT: 36800,
    amenities: ["Carry-on 7kg", "Long Haul Entertainment", "Japanese Bento Pre-order"]
  },
  {
    id: "FL-030",
    flightNumber: "D7-524",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "TYO",
    destinationCity: "Tokyo",
    destinationAirport: "Haneda Airport (HND)",
    daysAhead: 3,
    departureTime: "23:45",
    arrivalTime: "07:45",
    duration: "7h 00m",
    durationMinutes: 420,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A330-300",
    cabinClass: "Premium Flatbed",
    baggageAllowance: "40 kg check-in + 7 kg cabin",
    availableSeats: 5,
    baseFareBDT: 72000,
    taxBDT: 6500,
    priceBDT: 78500,
    amenities: ["Lie-Flat Bed", "40kg Baggage", "Gourmet Dining", "Priority Baggage & Boarding"]
  },

  // KUL <-> ICN (Kuala Lumpur to Seoul Incheon)
  {
    id: "FL-031",
    flightNumber: "D7-504",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "ICN",
    destinationCity: "Seoul",
    destinationAirport: "Incheon International Airport",
    daysAhead: 2,
    departureTime: "01:00",
    arrivalTime: "08:30",
    duration: "6h 30m",
    durationMinutes: 390,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A330-300",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 35,
    baseFareBDT: 29500,
    taxBDT: 4500,
    priceBDT: 34000,
    amenities: ["Carry-on 7kg", "Korean Meal Options", "Comfort Kit"]
  },

  // KUL <-> CGK (Kuala Lumpur to Jakarta)
  {
    id: "FL-032",
    flightNumber: "QZ-201",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "CGK",
    destinationCity: "Jakarta",
    destinationAirport: "Soekarno-Hatta International Airport",
    daysAhead: 1,
    departureTime: "08:30",
    arrivalTime: "09:35",
    duration: "2h 05m",
    durationMinutes: 125,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 42,
    baseFareBDT: 6800,
    taxBDT: 1600,
    priceBDT: 8400,
    amenities: ["Carry-on 7kg", "Quick Business Route"]
  },
  {
    id: "FL-033",
    flightNumber: "QZ-205",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "CGK",
    destinationCity: "Jakarta",
    destinationAirport: "Soekarno-Hatta International Airport",
    daysAhead: 2,
    departureTime: "16:50",
    arrivalTime: "17:55",
    duration: "2h 05m",
    durationMinutes: 125,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 31,
    baseFareBDT: 7200,
    taxBDT: 1600,
    priceBDT: 8800,
    amenities: ["Carry-on 7kg"]
  },

  // DAC <-> CGK (Dhaka to Jakarta via KUL)
  {
    id: "FL-034",
    flightNumber: "AK-512 / QZ-205",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "CGK",
    destinationCity: "Jakarta",
    destinationAirport: "Soekarno-Hatta International Airport",
    daysAhead: 1,
    departureTime: "01:25",
    arrivalTime: "11:45",
    duration: "9h 20m",
    durationMinutes: 560,
    stops: 1,
    stopsText: "1 Stop (KUL 3h 15m)",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 14,
    baseFareBDT: 26000,
    taxBDT: 3700,
    priceBDT: 29700,
    amenities: ["Carry-on 7kg", "Fly-Thru Connection"]
  },

  // DAC <-> DPS (Dhaka to Bali via KUL)
  {
    id: "FL-035",
    flightNumber: "AK-512 / QZ-551",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "DPS",
    destinationCity: "Bali",
    destinationAirport: "Ngurah Rai International Airport",
    daysAhead: 1,
    departureTime: "01:25",
    arrivalTime: "12:25",
    duration: "9h 00m",
    durationMinutes: 540,
    stops: 1,
    stopsText: "1 Stop (KUL 2h 10m)",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 16,
    baseFareBDT: 29500,
    taxBDT: 4200,
    priceBDT: 33700,
    amenities: ["Carry-on 7kg", "Fly-Thru Island Route"]
  },
  {
    id: "FL-036",
    flightNumber: "AK-514 / QZ-555",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "DPS",
    destinationCity: "Bali",
    destinationAirport: "Ngurah Rai International Airport",
    daysAhead: 2,
    departureTime: "12:40",
    arrivalTime: "23:55",
    duration: "9h 15m",
    durationMinutes: 555,
    stops: 1,
    stopsText: "1 Stop (KUL 2h 20m)",
    aircraft: "Airbus A321neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 18,
    baseFareBDT: 30800,
    taxBDT: 4200,
    priceBDT: 35000,
    amenities: ["Carry-on 7kg", "Hot Meal Pre-order"]
  },

  // KUL <-> LGK (Kuala Lumpur to Langkawi Domestic)
  {
    id: "FL-037",
    flightNumber: "AK-6302",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "LGK",
    destinationCity: "Langkawi",
    destinationAirport: "Langkawi International Airport",
    daysAhead: 1,
    departureTime: "08:15",
    arrivalTime: "09:20",
    duration: "1h 05m",
    durationMinutes: 65,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 48,
    baseFareBDT: 3500,
    taxBDT: 900,
    priceBDT: 4400,
    amenities: ["Carry-on 7kg", "Duty-Free Island Shuttle"]
  },
  {
    id: "FL-038",
    flightNumber: "AK-6316",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "LGK",
    destinationCity: "Langkawi",
    destinationAirport: "Langkawi International Airport",
    daysAhead: 2,
    departureTime: "14:40",
    arrivalTime: "15:45",
    duration: "1h 05m",
    durationMinutes: 65,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 35,
    baseFareBDT: 3800,
    taxBDT: 900,
    priceBDT: 4700,
    amenities: ["Carry-on 7kg"]
  },

  // KUL <-> BKI (Kuala Lumpur to Kota Kinabalu)
  {
    id: "FL-039",
    flightNumber: "AK-5104",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "BKI",
    destinationCity: "Kota Kinabalu",
    destinationAirport: "Kota Kinabalu International Airport",
    daysAhead: 1,
    departureTime: "11:20",
    arrivalTime: "14:00",
    duration: "2h 40m",
    durationMinutes: 160,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 30,
    baseFareBDT: 6500,
    taxBDT: 1400,
    priceBDT: 7900,
    amenities: ["Carry-on 7kg", "Borneo Gateway"]
  },

  // DAC <-> HKT (Dhaka to Phuket via BKK or KUL)
  {
    id: "FL-040",
    flightNumber: "FD-181 / FD-3025",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "HKT",
    destinationCity: "Phuket",
    destinationAirport: "Phuket International Airport",
    daysAhead: 2,
    departureTime: "02:10",
    arrivalTime: "09:30",
    duration: "6h 20m",
    durationMinutes: 380,
    stops: 1,
    stopsText: "1 Stop (DMK 2h 25m)",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 15,
    baseFareBDT: 22800,
    taxBDT: 3400,
    priceBDT: 26200,
    amenities: ["Carry-on 7kg", "Fly-Thru Andaman Route"]
  },

  // Business Class & First Class Fleet Additions
  {
    "id": "FL-041",
    "flightNumber": "AK-516",
    "airline": "AirAsia X",
    "origin": "DAC",
    "originCity": "Dhaka",
    "originAirport": "Hazrat Shahjalal Intl Airport",
    "destination": "KUL",
    "destinationCity": "Kuala Lumpur",
    "destinationAirport": "Kuala Lumpur International Airport (Terminal 2)",
    "daysAhead": 1,
    "departureTime": "03:15",
    "arrivalTime": "09:05",
    "duration": "3h 50m",
    "durationMinutes": 230,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Airbus A330-900neo",
    "cabinClass": "Business Class",
    "baggageAllowance": "40 kg check-in + 2x 7 kg cabin",
    "seatPitch": "64 inches • 180° Direct-Aisle Lie-Flat Suite",
    "availableSeats": 12,
    "baseFareBDT": 49500,
    "taxBDT": 4500,
    "priceBDT": 54000,
    "amenities": [
      "180° Lie-Flat Bed",
      "AirAsia Premium Lounge",
      "40kg Baggage",
      "Champagne & Fine Dining",
      "Priority Fast-Track"
    ]
  },
  {
    "id": "FL-042",
    "flightNumber": "D7-990",
    "airline": "AirAsia X Prestige",
    "origin": "DAC",
    "originCity": "Dhaka",
    "originAirport": "Hazrat Shahjalal Intl Airport",
    "destination": "KUL",
    "destinationCity": "Kuala Lumpur",
    "destinationAirport": "Kuala Lumpur International Airport (Terminal 2)",
    "daysAhead": 1,
    "departureTime": "23:45",
    "arrivalTime": "05:35",
    "duration": "3h 50m",
    "durationMinutes": 230,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Airbus A350-1000 Prestige Suite",
    "cabinClass": "First Class",
    "baggageAllowance": "50 kg check-in + 2x 10 kg cabin",
    "seatPitch": "78 inches • Private Enclosed Suite with Sliding Privacy Door",
    "availableSeats": 4,
    "baseFareBDT": 90000,
    "taxBDT": 8500,
    "priceBDT": 98500,
    "amenities": [
      "Private Sliding Door Suite",
      "VIP Chauffeur Service",
      "Dedicated Butler",
      "Caviar & Dom Pérignon",
      "50kg Baggage"
    ]
  },
  {
    "id": "FL-043",
    "flightNumber": "AK-517",
    "airline": "AirAsia X",
    "origin": "KUL",
    "originCity": "Kuala Lumpur",
    "originAirport": "Kuala Lumpur International Airport (Terminal 2)",
    "destination": "DAC",
    "destinationCity": "Dhaka",
    "destinationAirport": "Hazrat Shahjalal Intl Airport",
    "daysAhead": 1,
    "departureTime": "19:30",
    "arrivalTime": "21:25",
    "duration": "3h 55m",
    "durationMinutes": 235,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Airbus A330-900neo",
    "cabinClass": "Business Class",
    "baggageAllowance": "40 kg check-in + 2x 7 kg cabin",
    "seatPitch": "64 inches • 180° Direct-Aisle Lie-Flat Suite",
    "availableSeats": 10,
    "baseFareBDT": 49000,
    "taxBDT": 4500,
    "priceBDT": 53500,
    "amenities": [
      "180° Lie-Flat Bed",
      "AirAsia Premium Lounge",
      "40kg Baggage",
      "Executive Dining",
      "Priority Boarding"
    ]
  },
  {
    "id": "FL-044",
    "flightNumber": "D7-991",
    "airline": "AirAsia X Prestige",
    "origin": "KUL",
    "originCity": "Kuala Lumpur",
    "originAirport": "Kuala Lumpur International Airport (Terminal 2)",
    "destination": "DAC",
    "destinationCity": "Dhaka",
    "destinationAirport": "Hazrat Shahjalal Intl Airport",
    "daysAhead": 1,
    "departureTime": "08:15",
    "arrivalTime": "10:10",
    "duration": "3h 55m",
    "durationMinutes": 235,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Airbus A350-1000 Prestige Suite",
    "cabinClass": "First Class",
    "baggageAllowance": "50 kg check-in + 2x 10 kg cabin",
    "seatPitch": "78 inches • Private Enclosed Suite with Sliding Privacy Door",
    "availableSeats": 4,
    "baseFareBDT": 88000,
    "taxBDT": 8000,
    "priceBDT": 96000,
    "amenities": [
      "Private Sliding Door Suite",
      "VIP Chauffeur Service",
      "Dedicated Butler",
      "Caviar & Dom Pérignon",
      "50kg Baggage"
    ]
  },
  {
    "id": "FL-045",
    "flightNumber": "XJ-810",
    "airline": "Thai AirAsia X",
    "origin": "DAC",
    "originCity": "Dhaka",
    "originAirport": "Hazrat Shahjalal Intl Airport",
    "destination": "DMK",
    "destinationCity": "Bangkok",
    "destinationAirport": "Don Mueang Intl Airport",
    "daysAhead": 1,
    "departureTime": "11:30",
    "arrivalTime": "15:00",
    "duration": "2h 30m",
    "durationMinutes": 150,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Airbus A330neo",
    "cabinClass": "Business Class",
    "baggageAllowance": "40 kg check-in + 2x 7 kg cabin",
    "seatPitch": "64 inches • 180° Direct-Aisle Lie-Flat Suite",
    "availableSeats": 8,
    "baseFareBDT": 44000,
    "taxBDT": 4000,
    "priceBDT": 48000,
    "amenities": [
      "180° Lie-Flat Bed",
      "Bangkok Royal Lounge",
      "40kg Baggage",
      "Thai Gourmet Dining",
      "Fast Track"
    ]
  },
  {
    "id": "FL-046",
    "flightNumber": "XJ-992",
    "airline": "Thai AirAsia X Royal",
    "origin": "DAC",
    "originCity": "Dhaka",
    "originAirport": "Hazrat Shahjalal Intl Airport",
    "destination": "DMK",
    "destinationCity": "Bangkok",
    "destinationAirport": "Don Mueang Intl Airport",
    "daysAhead": 1,
    "departureTime": "20:15",
    "arrivalTime": "23:45",
    "duration": "2h 30m",
    "durationMinutes": 150,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Airbus A350-900 Royal Suite",
    "cabinClass": "First Class",
    "baggageAllowance": "50 kg check-in + 2x 10 kg cabin",
    "seatPitch": "78 inches • Private Enclosed Suite with Sliding Privacy Door",
    "availableSeats": 4,
    "baseFareBDT": 79000,
    "taxBDT": 7000,
    "priceBDT": 86000,
    "amenities": [
      "Private Suite",
      "Bangkok VIP Limousine",
      "Dedicated Butler",
      "Royal Thai Fine Dining",
      "Dom Pérignon"
    ]
  },
  {
    "id": "FL-047",
    "flightNumber": "XJ-811",
    "airline": "Thai AirAsia X",
    "origin": "DMK",
    "originCity": "Bangkok",
    "originAirport": "Don Mueang Intl Airport",
    "destination": "DAC",
    "destinationCity": "Dhaka",
    "destinationAirport": "Hazrat Shahjalal Intl Airport",
    "daysAhead": 1,
    "departureTime": "07:45",
    "arrivalTime": "09:15",
    "duration": "2h 30m",
    "durationMinutes": 150,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Airbus A330neo",
    "cabinClass": "Business Class",
    "baggageAllowance": "40 kg check-in + 2x 7 kg cabin",
    "seatPitch": "64 inches • 180° Direct-Aisle Lie-Flat Suite",
    "availableSeats": 8,
    "baseFareBDT": 43500,
    "taxBDT": 4000,
    "priceBDT": 47500,
    "amenities": [
      "180° Lie-Flat Bed",
      "Don Mueang Executive Lounge",
      "40kg Baggage",
      "Gourmet Dining"
    ]
  },
  {
    "id": "FL-048",
    "flightNumber": "XJ-993",
    "airline": "Thai AirAsia X Royal",
    "origin": "DMK",
    "originCity": "Bangkok",
    "originAirport": "Don Mueang Intl Airport",
    "destination": "DAC",
    "destinationCity": "Dhaka",
    "destinationAirport": "Hazrat Shahjalal Intl Airport",
    "daysAhead": 1,
    "departureTime": "16:30",
    "arrivalTime": "18:00",
    "duration": "2h 30m",
    "durationMinutes": 150,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Airbus A350-900 Royal Suite",
    "cabinClass": "First Class",
    "baggageAllowance": "50 kg check-in + 2x 10 kg cabin",
    "seatPitch": "78 inches • Private Enclosed Suite with Sliding Privacy Door",
    "availableSeats": 4,
    "baseFareBDT": 78500,
    "taxBDT": 7000,
    "priceBDT": 85500,
    "amenities": [
      "Private Suite",
      "Airport Limousine",
      "Fine Dining",
      "Dom Pérignon",
      "50kg Baggage"
    ]
  },
  {
    "id": "FL-049",
    "flightNumber": "AK-702",
    "airline": "AirAsia Executive",
    "origin": "KUL",
    "originCity": "Kuala Lumpur",
    "originAirport": "Kuala Lumpur International Airport (Terminal 2)",
    "destination": "SIN",
    "destinationCity": "Singapore",
    "destinationAirport": "Singapore Changi Airport",
    "daysAhead": 1,
    "departureTime": "08:00",
    "arrivalTime": "08:55",
    "duration": "55m",
    "durationMinutes": 55,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Airbus A321neo Executive",
    "cabinClass": "Business Class",
    "baggageAllowance": "40 kg check-in + 2x 7 kg cabin",
    "seatPitch": "42 inches • Wide Executive Recliner",
    "availableSeats": 16,
    "baseFareBDT": 20000,
    "taxBDT": 2500,
    "priceBDT": 22500,
    "amenities": [
      "KLIA2 Plaza Premium Lounge",
      "Express Clearance",
      "Santan Chef Plate",
      "Priority Boarding"
    ]
  },
  {
    "id": "FL-050",
    "flightNumber": "AK-710",
    "airline": "AirAsia Diamond",
    "origin": "KUL",
    "originCity": "Kuala Lumpur",
    "originAirport": "Kuala Lumpur International Airport (Terminal 2)",
    "destination": "SIN",
    "destinationCity": "Singapore",
    "destinationAirport": "Singapore Changi Airport",
    "daysAhead": 1,
    "departureTime": "17:30",
    "arrivalTime": "18:25",
    "duration": "55m",
    "durationMinutes": 55,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Boeing 787-9 Diamond Dreamliner",
    "cabinClass": "First Class",
    "baggageAllowance": "50 kg check-in + 2x 10 kg cabin",
    "seatPitch": "78 inches • Private Enclosed Suite with Sliding Privacy Door",
    "availableSeats": 4,
    "baseFareBDT": 40000,
    "taxBDT": 4000,
    "priceBDT": 44000,
    "amenities": [
      "Private Suite",
      "Changi JetQuay Terminal",
      "Dom Pérignon",
      "Personal Concierge"
    ]
  },
  {
    "id": "FL-051",
    "flightNumber": "AK-703",
    "airline": "AirAsia Executive",
    "origin": "SIN",
    "originCity": "Singapore",
    "originAirport": "Singapore Changi Airport",
    "destination": "KUL",
    "destinationCity": "Kuala Lumpur",
    "destinationAirport": "Kuala Lumpur International Airport (Terminal 2)",
    "daysAhead": 1,
    "departureTime": "10:15",
    "arrivalTime": "11:10",
    "duration": "55m",
    "durationMinutes": 55,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Airbus A321neo Executive",
    "cabinClass": "Business Class",
    "baggageAllowance": "40 kg check-in + 2x 7 kg cabin",
    "seatPitch": "42 inches • Wide Executive Recliner",
    "availableSeats": 14,
    "baseFareBDT": 19500,
    "taxBDT": 2500,
    "priceBDT": 22000,
    "amenities": [
      "Changi SATS Premier Lounge",
      "Express Boarding",
      "Gourmet Snack",
      "40kg Baggage"
    ]
  },
  {
    "id": "FL-052",
    "flightNumber": "AK-711",
    "airline": "AirAsia Diamond",
    "origin": "SIN",
    "originCity": "Singapore",
    "originAirport": "Singapore Changi Airport",
    "destination": "KUL",
    "destinationCity": "Kuala Lumpur",
    "destinationAirport": "Kuala Lumpur International Airport (Terminal 2)",
    "daysAhead": 1,
    "departureTime": "19:40",
    "arrivalTime": "20:35",
    "duration": "55m",
    "durationMinutes": 55,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Boeing 787-9 Diamond Dreamliner",
    "cabinClass": "First Class",
    "baggageAllowance": "50 kg check-in + 2x 10 kg cabin",
    "seatPitch": "78 inches • Private Enclosed Suite with Sliding Privacy Door",
    "availableSeats": 4,
    "baseFareBDT": 39500,
    "taxBDT": 4000,
    "priceBDT": 43500,
    "amenities": [
      "Private Suite",
      "Singapore Limousine",
      "Fine Dining",
      "Dom Pérignon"
    ]
  },
  {
    "id": "FL-053",
    "flightNumber": "D7-792",
    "airline": "AirAsia X Bali Luxe",
    "origin": "KUL",
    "originCity": "Kuala Lumpur",
    "originAirport": "Kuala Lumpur International Airport (Terminal 2)",
    "destination": "DPS",
    "destinationCity": "Bali",
    "destinationAirport": "Ngurah Rai Intl Airport (Denpasar)",
    "daysAhead": 1,
    "departureTime": "10:20",
    "arrivalTime": "13:20",
    "duration": "3h 00m",
    "durationMinutes": 180,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Airbus A330-900neo",
    "cabinClass": "Business Class",
    "baggageAllowance": "40 kg check-in + 2x 7 kg cabin",
    "seatPitch": "64 inches • 180° Direct-Aisle Lie-Flat Suite",
    "availableSeats": 12,
    "baseFareBDT": 32500,
    "taxBDT": 3500,
    "priceBDT": 36000,
    "amenities": [
      "180° Lie-Flat Bed",
      "KLIA2 Premium Lounge",
      "Tropical Welcome Cocktail",
      "Priority Luggage"
    ]
  },
  {
    "id": "FL-054",
    "flightNumber": "D7-798",
    "airline": "AirAsia X Presidential",
    "origin": "KUL",
    "originCity": "Kuala Lumpur",
    "originAirport": "Kuala Lumpur International Airport (Terminal 2)",
    "destination": "DPS",
    "destinationCity": "Bali",
    "destinationAirport": "Ngurah Rai Intl Airport (Denpasar)",
    "daysAhead": 1,
    "departureTime": "15:45",
    "arrivalTime": "18:45",
    "duration": "3h 00m",
    "durationMinutes": 180,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Airbus A350 Presidential Suite",
    "cabinClass": "First Class",
    "baggageAllowance": "50 kg check-in + 2x 10 kg cabin",
    "seatPitch": "78 inches • Private Enclosed Suite with Sliding Privacy Door",
    "availableSeats": 4,
    "baseFareBDT": 66000,
    "taxBDT": 6000,
    "priceBDT": 72000,
    "amenities": [
      "Private Suite",
      "Bali Resort Chauffeur",
      "Caviar Service",
      "Dom Pérignon",
      "Personal Butler"
    ]
  },
  {
    "id": "FL-055",
    "flightNumber": "D7-793",
    "airline": "AirAsia X Bali Luxe",
    "origin": "DPS",
    "originCity": "Bali",
    "originAirport": "Ngurah Rai Intl Airport (Denpasar)",
    "destination": "KUL",
    "destinationCity": "Kuala Lumpur",
    "destinationAirport": "Kuala Lumpur International Airport (Terminal 2)",
    "daysAhead": 1,
    "departureTime": "14:15",
    "arrivalTime": "17:15",
    "duration": "3h 00m",
    "durationMinutes": 180,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Airbus A330-900neo",
    "cabinClass": "Business Class",
    "baggageAllowance": "40 kg check-in + 2x 7 kg cabin",
    "seatPitch": "64 inches • 180° Direct-Aisle Lie-Flat Suite",
    "availableSeats": 10,
    "baseFareBDT": 32000,
    "taxBDT": 3500,
    "priceBDT": 35500,
    "amenities": [
      "180° Lie-Flat Bed",
      "Denpasar T/G Lounge",
      "Balinese Gourmet Dining",
      "Fast Track"
    ]
  },
  {
    "id": "FL-056",
    "flightNumber": "D7-799",
    "airline": "AirAsia X Presidential",
    "origin": "DPS",
    "originCity": "Bali",
    "originAirport": "Ngurah Rai Intl Airport (Denpasar)",
    "destination": "KUL",
    "destinationCity": "Kuala Lumpur",
    "destinationAirport": "Kuala Lumpur International Airport (Terminal 2)",
    "daysAhead": 1,
    "departureTime": "19:40",
    "arrivalTime": "22:40",
    "duration": "3h 00m",
    "durationMinutes": 180,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Airbus A350 Presidential Suite",
    "cabinClass": "First Class",
    "baggageAllowance": "50 kg check-in + 2x 10 kg cabin",
    "seatPitch": "78 inches • Private Enclosed Suite with Sliding Privacy Door",
    "availableSeats": 4,
    "baseFareBDT": 65500,
    "taxBDT": 6000,
    "priceBDT": 71500,
    "amenities": [
      "Private Suite",
      "Bali Airport VIP Transfer",
      "Chef Service",
      "Dom Pérignon",
      "50kg Baggage"
    ]
  },
  {
    "id": "FL-057",
    "flightNumber": "AK-388",
    "airline": "AirAsia Executive",
    "origin": "KUL",
    "originCity": "Kuala Lumpur",
    "originAirport": "Kuala Lumpur International Airport (Terminal 2)",
    "destination": "CGK",
    "destinationCity": "Jakarta",
    "destinationAirport": "Soekarno-Hatta Intl Airport",
    "daysAhead": 1,
    "departureTime": "09:10",
    "arrivalTime": "10:10",
    "duration": "2h 00m",
    "durationMinutes": 120,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Airbus A330-300",
    "cabinClass": "Business Class",
    "baggageAllowance": "40 kg check-in + 2x 7 kg cabin",
    "seatPitch": "64 inches • 180° Direct-Aisle Lie-Flat Suite",
    "availableSeats": 12,
    "baseFareBDT": 25000,
    "taxBDT": 3000,
    "priceBDT": 28000,
    "amenities": [
      "180° Lie-Flat Bed",
      "Executive Lounge",
      "Fine Dining",
      "Priority Baggage"
    ]
  },
  {
    "id": "FL-058",
    "flightNumber": "QZ-902",
    "airline": "Indonesia AirAsia Royal",
    "origin": "KUL",
    "originCity": "Kuala Lumpur",
    "originAirport": "Kuala Lumpur International Airport (Terminal 2)",
    "destination": "CGK",
    "destinationCity": "Jakarta",
    "destinationAirport": "Soekarno-Hatta Intl Airport",
    "daysAhead": 1,
    "departureTime": "16:00",
    "arrivalTime": "17:00",
    "duration": "2h 00m",
    "durationMinutes": 120,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Boeing 787-9 Royal First",
    "cabinClass": "First Class",
    "baggageAllowance": "50 kg check-in + 2x 10 kg cabin",
    "seatPitch": "78 inches • Private Enclosed Suite with Sliding Privacy Door",
    "availableSeats": 4,
    "baseFareBDT": 53000,
    "taxBDT": 5000,
    "priceBDT": 58000,
    "amenities": [
      "Private Suite",
      "Jakarta VIP Limousine",
      "Fine Dining",
      "Dom Pérignon"
    ]
  },
  {
    "id": "FL-059",
    "flightNumber": "AK-389",
    "airline": "AirAsia Executive",
    "origin": "CGK",
    "originCity": "Jakarta",
    "originAirport": "Soekarno-Hatta Intl Airport",
    "destination": "KUL",
    "destinationCity": "Kuala Lumpur",
    "destinationAirport": "Kuala Lumpur International Airport (Terminal 2)",
    "daysAhead": 1,
    "departureTime": "11:20",
    "arrivalTime": "14:20",
    "duration": "2h 00m",
    "durationMinutes": 120,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Airbus A330-300",
    "cabinClass": "Business Class",
    "baggageAllowance": "40 kg check-in + 2x 7 kg cabin",
    "seatPitch": "64 inches • 180° Direct-Aisle Lie-Flat Suite",
    "availableSeats": 12,
    "baseFareBDT": 24500,
    "taxBDT": 3000,
    "priceBDT": 27500,
    "amenities": [
      "180° Lie-Flat Bed",
      "Jakarta Saphire Lounge",
      "Fine Dining",
      "40kg Baggage"
    ]
  },
  {
    "id": "FL-060",
    "flightNumber": "QZ-903",
    "airline": "Indonesia AirAsia Royal",
    "origin": "CGK",
    "originCity": "Jakarta",
    "originAirport": "Soekarno-Hatta Intl Airport",
    "destination": "KUL",
    "destinationCity": "Kuala Lumpur",
    "destinationAirport": "Kuala Lumpur International Airport (Terminal 2)",
    "daysAhead": 1,
    "departureTime": "18:15",
    "arrivalTime": "21:15",
    "duration": "2h 00m",
    "durationMinutes": 120,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Boeing 787-9 Royal First",
    "cabinClass": "First Class",
    "baggageAllowance": "50 kg check-in + 2x 10 kg cabin",
    "seatPitch": "78 inches • Private Enclosed Suite with Sliding Privacy Door",
    "availableSeats": 4,
    "baseFareBDT": 52500,
    "taxBDT": 5000,
    "priceBDT": 57500,
    "amenities": [
      "Private Suite",
      "VIP Transfer",
      "Caviar & Fine Dining",
      "50kg Baggage"
    ]
  },
  {
    "id": "FL-064",
    "flightNumber": "AK-512 / D7-792",
    "airline": "AirAsia X",
    "origin": "DAC",
    "originCity": "Dhaka",
    "originAirport": "Hazrat Shahjalal Intl Airport",
    "destination": "DPS",
    "destinationCity": "Bali",
    "destinationAirport": "Ngurah Rai Intl Airport (Denpasar)",
    "daysAhead": 1,
    "departureTime": "01:25",
    "arrivalTime": "13:20",
    "duration": "9h 55m",
    "durationMinutes": 595,
    "stops": 1,
    "stopsText": "1 Stop (KUL 3h 05m)",
    "aircraft": "Airbus A330-900neo",
    "cabinClass": "Business Class",
    "baggageAllowance": "40 kg check-in + 2x 7 kg cabin",
    "seatPitch": "64 inches • 180° Direct-Aisle Lie-Flat Suite",
    "availableSeats": 8,
    "baseFareBDT": 56000,
    "taxBDT": 6000,
    "priceBDT": 62000,
    "amenities": [
      "180° Lie-Flat Bed",
      "KUL Plaza Premium Lounge",
      "40kg Luggage",
      "Champagne Dining"
    ]
  },
  {
    "id": "FL-065",
    "flightNumber": "D7-990 / D7-798",
    "airline": "AirAsia X Prestige",
    "origin": "DAC",
    "originCity": "Dhaka",
    "originAirport": "Hazrat Shahjalal Intl Airport",
    "destination": "DPS",
    "destinationCity": "Bali",
    "destinationAirport": "Ngurah Rai Intl Airport (Denpasar)",
    "daysAhead": 1,
    "departureTime": "23:45",
    "arrivalTime": "18:45",
    "duration": "17h 00m",
    "durationMinutes": 1020,
    "stops": 1,
    "stopsText": "1 Stop (KUL VIP Lounge 10h 10m)",
    "aircraft": "Airbus A350-1000 Prestige Suite",
    "cabinClass": "First Class",
    "baggageAllowance": "50 kg check-in + 2x 10 kg cabin",
    "seatPitch": "78 inches • Private Enclosed Suite with Sliding Privacy Door",
    "availableSeats": 4,
    "baseFareBDT": 102000,
    "taxBDT": 10000,
    "priceBDT": 112000,
    "amenities": [
      "Private Suite",
      "Airport Limousine",
      "Private Airport Transit Suite",
      "Caviar & Champagne"
    ]
  },
  {
    "id": "FL-066",
    "flightNumber": "D7-793 / AK-517",
    "airline": "AirAsia X",
    "origin": "DPS",
    "originCity": "Bali",
    "originAirport": "Ngurah Rai Intl Airport (Denpasar)",
    "destination": "DAC",
    "destinationCity": "Dhaka",
    "destinationAirport": "Hazrat Shahjalal Intl Airport",
    "daysAhead": 1,
    "departureTime": "14:15",
    "arrivalTime": "21:25",
    "duration": "9h 10m",
    "durationMinutes": 550,
    "stops": 1,
    "stopsText": "1 Stop (KUL 2h 15m)",
    "aircraft": "Airbus A330-900neo",
    "cabinClass": "Business Class",
    "baggageAllowance": "40 kg check-in + 2x 7 kg cabin",
    "seatPitch": "64 inches • 180° Direct-Aisle Lie-Flat Suite",
    "availableSeats": 8,
    "baseFareBDT": 55500,
    "taxBDT": 6000,
    "priceBDT": 61500,
    "amenities": [
      "180° Lie-Flat Bed",
      "KUL Plaza Premium Lounge",
      "40kg Luggage",
      "Gourmet Dining"
    ]
  },
  {
    "id": "FL-061",
    "flightNumber": "AK-512 / AK-708",
    "airline": "AirAsia Executive",
    "origin": "DAC",
    "originCity": "Dhaka",
    "originAirport": "Hazrat Shahjalal Intl Airport",
    "destination": "SIN",
    "destinationCity": "Singapore",
    "destinationAirport": "Singapore Changi Airport",
    "daysAhead": 1,
    "departureTime": "01:25",
    "arrivalTime": "09:30",
    "duration": "6h 05m",
    "durationMinutes": 365,
    "stops": 1,
    "stopsText": "1 Stop (KUL 1h 15m)",
    "aircraft": "Airbus A330 / A321neo Executive",
    "cabinClass": "Business Class",
    "baggageAllowance": "40 kg check-in + 2x 7 kg cabin",
    "seatPitch": "64 inches • 180° Direct-Aisle Lie-Flat Suite",
    "availableSeats": 10,
    "baseFareBDT": 51000,
    "taxBDT": 5000,
    "priceBDT": 56000,
    "amenities": [
      "Lie-Flat Seating",
      "Changi & KLIA Lounge",
      "40kg Baggage",
      "Executive Dining"
    ]
  },
  {
    "id": "FL-062",
    "flightNumber": "D7-994",
    "airline": "AirAsia X Prestige",
    "origin": "DAC",
    "originCity": "Dhaka",
    "originAirport": "Hazrat Shahjalal Intl Airport",
    "destination": "SIN",
    "destinationCity": "Singapore",
    "destinationAirport": "Singapore Changi Airport",
    "daysAhead": 1,
    "departureTime": "21:00",
    "arrivalTime": "03:15",
    "duration": "4h 15m",
    "durationMinutes": 255,
    "stops": 0,
    "stopsText": "Direct",
    "aircraft": "Airbus A350-1000 Prestige Suite",
    "cabinClass": "First Class",
    "baggageAllowance": "50 kg check-in + 2x 10 kg cabin",
    "seatPitch": "78 inches • Private Enclosed Suite with Sliding Privacy Door",
    "availableSeats": 4,
    "baseFareBDT": 84000,
    "taxBDT": 8000,
    "priceBDT": 92000,
    "amenities": [
      "Private Suite",
      "Singapore Limousine",
      "Dedicated Butler",
      "Caviar & Dom Pérignon"
    ]
  },
  {
    "id": "FL-063",
    "flightNumber": "AK-709 / AK-517",
    "airline": "AirAsia Executive",
    "origin": "SIN",
    "originCity": "Singapore",
    "originAirport": "Singapore Changi Airport",
    "destination": "DAC",
    "destinationCity": "Dhaka",
    "destinationAirport": "Hazrat Shahjalal Intl Airport",
    "daysAhead": 1,
    "departureTime": "15:30",
    "arrivalTime": "21:25",
    "duration": "7h 55m",
    "durationMinutes": 475,
    "stops": 1,
    "stopsText": "1 Stop (KUL 2h 55m)",
    "aircraft": "Airbus A330 / A321neo Executive",
    "cabinClass": "Business Class",
    "baggageAllowance": "40 kg check-in + 2x 7 kg cabin",
    "seatPitch": "64 inches • 180° Direct-Aisle Lie-Flat Suite",
    "availableSeats": 10,
    "baseFareBDT": 50000,
    "taxBDT": 5000,
    "priceBDT": 55000,
    "amenities": [
      "Lie-Flat Seating",
      "Changi Lounge Access",
      "40kg Baggage",
      "Executive Dining"
    ]
  },
  {
    "id": "FL-067",
    "flightNumber": "AK-512 / AK-388",
    "airline": "AirAsia Executive",
    "origin": "DAC",
    "originCity": "Dhaka",
    "originAirport": "Hazrat Shahjalal Intl Airport",
    "destination": "CGK",
    "destinationCity": "Jakarta",
    "destinationAirport": "Soekarno-Hatta Intl Airport",
    "daysAhead": 1,
    "departureTime": "01:25",
    "arrivalTime": "10:10",
    "duration": "6h 45m",
    "durationMinutes": 405,
    "stops": 1,
    "stopsText": "1 Stop (KUL 1h 55m)",
    "aircraft": "Airbus A330-300 Executive",
    "cabinClass": "Business Class",
    "baggageAllowance": "40 kg check-in + 2x 7 kg cabin",
    "seatPitch": "64 inches • 180° Direct-Aisle Lie-Flat Suite",
    "availableSeats": 8,
    "baseFareBDT": 46000,
    "taxBDT": 5000,
    "priceBDT": 51000,
    "amenities": [
      "180° Lie-Flat Bed",
      "Lounge Access",
      "40kg Baggage",
      "Gourmet Dining"
    ]
  },
  {
    "id": "FL-068",
    "flightNumber": "AK-389 / AK-517",
    "airline": "AirAsia Executive",
    "origin": "CGK",
    "originCity": "Jakarta",
    "originAirport": "Soekarno-Hatta Intl Airport",
    "destination": "DAC",
    "destinationCity": "Dhaka",
    "destinationAirport": "Hazrat Shahjalal Intl Airport",
    "daysAhead": 1,
    "departureTime": "11:20",
    "arrivalTime": "21:25",
    "duration": "8h 05m",
    "durationMinutes": 485,
    "stops": 1,
    "stopsText": "1 Stop (KUL 5h 10m)",
    "aircraft": "Airbus A330-300 Executive",
    "cabinClass": "Business Class",
    "baggageAllowance": "40 kg check-in + 2x 7 kg cabin",
    "seatPitch": "64 inches • 180° Direct-Aisle Lie-Flat Suite",
    "availableSeats": 8,
    "baseFareBDT": 45500,
    "taxBDT": 5000,
    "priceBDT": 50500,
    "amenities": [
      "180° Lie-Flat Bed",
      "Jakarta Saphire Lounge",
      "40kg Baggage",
      "Gourmet Dining"
    ]
  }
];
