/**
 * AirAsia Local Sample Flight Data
 * Fully offline, frontend-only demonstration dataset.
 * Contains 40+ realistic sample flights across major AirAsia domestic and international routes.
 * No external APIs, databases, or backend services required.
 */

window.AIRASIA_FLIGHTS_DATA = [
  // DAC <-> KUL (Dhaka to Kuala Lumpur)
  {
    id: "FL-001",
    flightNumber: "AK-512",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "KUL",
    destinationCity: "Kuala Lumpur",
    destinationAirport: "Kuala Lumpur International Airport (Terminal 2)",
    daysAhead: 1,
    departureTime: "01:25",
    arrivalTime: "07:15",
    duration: "3h 50m",
    durationMinutes: 230,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 18,
    baseFareBDT: 21500,
    taxBDT: 3000,
    priceBDT: 24500,
    amenities: ["Carry-on 7kg", "USB Charging", "In-flight Purchase"]
  },
  {
    id: "FL-002",
    flightNumber: "AK-514",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "KUL",
    destinationCity: "Kuala Lumpur",
    destinationAirport: "Kuala Lumpur International Airport (Terminal 2)",
    daysAhead: 1,
    departureTime: "12:40",
    arrivalTime: "18:35",
    duration: "3h 55m",
    durationMinutes: 235,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A321neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 32,
    baseFareBDT: 23200,
    taxBDT: 3100,
    priceBDT: 26300,
    amenities: ["Carry-on 7kg", "Hot Meal Pre-order", "Comfort Seats"]
  },
  {
    id: "FL-003",
    flightNumber: "D7-182",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "KUL",
    destinationCity: "Kuala Lumpur",
    destinationAirport: "Kuala Lumpur International Airport (Terminal 2)",
    daysAhead: 1,
    departureTime: "22:15",
    arrivalTime: "04:10",
    duration: "3h 55m",
    durationMinutes: 235,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A330-300",
    cabinClass: "Premium Flatbed",
    baggageAllowance: "40 kg check-in + 7 kg cabin",
    availableSeats: 8,
    baseFareBDT: 54000,
    taxBDT: 4500,
    priceBDT: 58500,
    amenities: ["Flatbed Seat", "40kg Baggage", "Complimentary Meal", "Priority Boarding"]
  },
  {
    id: "FL-004",
    flightNumber: "AK-516",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "KUL",
    destinationCity: "Kuala Lumpur",
    destinationAirport: "Kuala Lumpur International Airport (Terminal 2)",
    daysAhead: 2,
    departureTime: "08:15",
    arrivalTime: "14:10",
    duration: "3h 55m",
    durationMinutes: 235,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 24,
    baseFareBDT: 20500,
    taxBDT: 3000,
    priceBDT: 23500,
    amenities: ["Carry-on 7kg", "Santan Café"]
  },
  {
    id: "FL-005",
    flightNumber: "AK-518",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "KUL",
    destinationCity: "Kuala Lumpur",
    destinationAirport: "Kuala Lumpur International Airport (Terminal 2)",
    daysAhead: 3,
    departureTime: "16:20",
    arrivalTime: "22:15",
    duration: "3h 55m",
    durationMinutes: 235,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A321neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 14,
    baseFareBDT: 22000,
    taxBDT: 3000,
    priceBDT: 25000,
    amenities: ["Carry-on 7kg", "Extra Legroom Options"]
  },

  // KUL <-> DAC (Kuala Lumpur to Dhaka - Returns & Reverse)
  {
    id: "FL-006",
    flightNumber: "AK-513",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "DAC",
    destinationCity: "Dhaka",
    destinationAirport: "Hazrat Shahjalal Intl Airport",
    daysAhead: 4,
    departureTime: "09:30",
    arrivalTime: "11:20",
    duration: "3h 50m",
    durationMinutes: 230,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 26,
    baseFareBDT: 21000,
    taxBDT: 3200,
    priceBDT: 24200,
    amenities: ["Carry-on 7kg", "Santan Meals"]
  },
  {
    id: "FL-007",
    flightNumber: "AK-515",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "DAC",
    destinationCity: "Dhaka",
    destinationAirport: "Hazrat Shahjalal Intl Airport",
    daysAhead: 4,
    departureTime: "19:45",
    arrivalTime: "21:35",
    duration: "3h 50m",
    durationMinutes: 230,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A321neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 15,
    baseFareBDT: 22500,
    taxBDT: 3200,
    priceBDT: 25700,
    amenities: ["Carry-on 7kg", "Power Outlets"]
  },
  {
    id: "FL-008",
    flightNumber: "D7-183",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "DAC",
    destinationCity: "Dhaka",
    destinationAirport: "Hazrat Shahjalal Intl Airport",
    daysAhead: 5,
    departureTime: "17:10",
    arrivalTime: "19:05",
    duration: "3h 55m",
    durationMinutes: 235,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A330-300",
    cabinClass: "Premium Flatbed",
    baggageAllowance: "40 kg check-in + 7 kg cabin",
    availableSeats: 6,
    baseFareBDT: 55000,
    taxBDT: 4500,
    priceBDT: 59500,
    amenities: ["Flatbed Seat", "40kg Baggage", "Complimentary Meal", "Lounge Access"]
  },

  // DAC <-> BKK (Dhaka to Bangkok)
  {
    id: "FL-009",
    flightNumber: "FD-181",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "BKK",
    destinationCity: "Bangkok",
    destinationAirport: "Don Mueang International Airport (DMK)",
    daysAhead: 1,
    departureTime: "02:10",
    arrivalTime: "05:40",
    duration: "2h 30m",
    durationMinutes: 150,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 22,
    baseFareBDT: 16500,
    taxBDT: 2700,
    priceBDT: 19200,
    amenities: ["Carry-on 7kg", "Thai Street Food Menu"]
  },
  {
    id: "FL-010",
    flightNumber: "FD-183",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "BKK",
    destinationCity: "Bangkok",
    destinationAirport: "Don Mueang International Airport (DMK)",
    daysAhead: 1,
    departureTime: "15:45",
    arrivalTime: "19:15",
    duration: "2h 30m",
    durationMinutes: 150,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A321neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 19,
    baseFareBDT: 17800,
    taxBDT: 2700,
    priceBDT: 20500,
    amenities: ["Carry-on 7kg", "Hot Seats Available"]
  },
  {
    id: "FL-011",
    flightNumber: "FD-182",
    origin: "BKK",
    originCity: "Bangkok",
    originAirport: "Don Mueang International Airport (DMK)",
    destination: "DAC",
    destinationCity: "Dhaka",
    destinationAirport: "Hazrat Shahjalal Intl Airport",
    daysAhead: 4,
    departureTime: "23:25",
    arrivalTime: "01:00",
    duration: "2h 35m",
    durationMinutes: 155,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 28,
    baseFareBDT: 16000,
    taxBDT: 2800,
    priceBDT: 18800,
    amenities: ["Carry-on 7kg", "Duty Free Shopping"]
  },

  // DAC <-> SIN (Dhaka to Singapore via KUL or Direct)
  {
    id: "FL-012",
    flightNumber: "AK-512 / AK-705",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "SIN",
    destinationCity: "Singapore",
    destinationAirport: "Singapore Changi Airport",
    daysAhead: 1,
    departureTime: "01:25",
    arrivalTime: "10:15",
    duration: "6h 50m",
    durationMinutes: 410,
    stops: 1,
    stopsText: "1 Stop (KUL 1h 45m)",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 14,
    baseFareBDT: 25000,
    taxBDT: 3800,
    priceBDT: 28800,
    amenities: ["Carry-on 7kg", "Fly-Thru Luggage Transfer"]
  },
  {
    id: "FL-013",
    flightNumber: "AK-514 / AK-711",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "SIN",
    destinationCity: "Singapore",
    destinationAirport: "Singapore Changi Airport",
    daysAhead: 2,
    departureTime: "12:40",
    arrivalTime: "21:30",
    duration: "6h 50m",
    durationMinutes: 410,
    stops: 1,
    stopsText: "1 Stop (KUL 1h 50m)",
    aircraft: "Airbus A321neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 20,
    baseFareBDT: 26500,
    taxBDT: 3800,
    priceBDT: 30300,
    amenities: ["Carry-on 7kg", "Fly-Thru Transfer", "Hot Meals"]
  },
  {
    id: "FL-014",
    flightNumber: "AK-706 / AK-515",
    origin: "SIN",
    originCity: "Singapore",
    originAirport: "Singapore Changi Airport",
    destination: "DAC",
    destinationCity: "Dhaka",
    destinationAirport: "Hazrat Shahjalal Intl Airport",
    daysAhead: 5,
    departureTime: "16:20",
    arrivalTime: "21:35",
    duration: "7h 15m",
    durationMinutes: 435,
    stops: 1,
    stopsText: "1 Stop (KUL 2h 10m)",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 16,
    baseFareBDT: 25500,
    taxBDT: 3900,
    priceBDT: 29400,
    amenities: ["Carry-on 7kg", "Changi Terminal Transfer"]
  },

  // KUL <-> SIN (Kuala Lumpur to Singapore)
  {
    id: "FL-015",
    flightNumber: "AK-701",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "SIN",
    destinationCity: "Singapore",
    destinationAirport: "Singapore Changi Airport",
    daysAhead: 1,
    departureTime: "07:05",
    arrivalTime: "08:15",
    duration: "1h 10m",
    durationMinutes: 70,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 45,
    baseFareBDT: 4800,
    taxBDT: 1500,
    priceBDT: 6300,
    amenities: ["Carry-on 7kg", "Express Shuttle Route"]
  },
  {
    id: "FL-016",
    flightNumber: "AK-705",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "SIN",
    destinationCity: "Singapore",
    destinationAirport: "Singapore Changi Airport",
    daysAhead: 1,
    departureTime: "14:15",
    arrivalTime: "15:25",
    duration: "1h 10m",
    durationMinutes: 70,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 30,
    baseFareBDT: 5200,
    taxBDT: 1500,
    priceBDT: 6700,
    amenities: ["Carry-on 7kg", "Hot Snack Options"]
  },
  {
    id: "FL-017",
    flightNumber: "AK-717",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "SIN",
    destinationCity: "Singapore",
    destinationAirport: "Singapore Changi Airport",
    daysAhead: 2,
    departureTime: "20:30",
    arrivalTime: "21:40",
    duration: "1h 10m",
    durationMinutes: 70,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 22,
    baseFareBDT: 4500,
    taxBDT: 1500,
    priceBDT: 6000,
    amenities: ["Carry-on 7kg"]
  },
  {
    id: "FL-018",
    flightNumber: "AK-702",
    origin: "SIN",
    originCity: "Singapore",
    originAirport: "Singapore Changi Airport",
    destination: "KUL",
    destinationCity: "Kuala Lumpur",
    destinationAirport: "Kuala Lumpur International Airport (Terminal 2)",
    daysAhead: 3,
    departureTime: "09:00",
    arrivalTime: "10:10",
    duration: "1h 10m",
    durationMinutes: 70,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 38,
    baseFareBDT: 4900,
    taxBDT: 1600,
    priceBDT: 6500,
    amenities: ["Carry-on 7kg"]
  },

  // KUL <-> DPS (Kuala Lumpur to Bali)
  {
    id: "FL-019",
    flightNumber: "QZ-551",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "DPS",
    destinationCity: "Bali",
    destinationAirport: "Ngurah Rai International Airport",
    daysAhead: 1,
    departureTime: "09:20",
    arrivalTime: "12:25",
    duration: "3h 05m",
    durationMinutes: 185,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 16,
    baseFareBDT: 13500,
    taxBDT: 2400,
    priceBDT: 15900,
    amenities: ["Carry-on 7kg", "Tropical Refreshments"]
  },
  {
    id: "FL-020",
    flightNumber: "D7-798",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "DPS",
    destinationCity: "Bali",
    destinationAirport: "Ngurah Rai International Airport",
    daysAhead: 2,
    departureTime: "15:40",
    arrivalTime: "18:45",
    duration: "3h 05m",
    durationMinutes: 185,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A330-300",
    cabinClass: "Premium Flatbed",
    baggageAllowance: "40 kg check-in + 7 kg cabin",
    availableSeats: 4,
    baseFareBDT: 38000,
    taxBDT: 3500,
    priceBDT: 41500,
    amenities: ["Flatbed Comfort", "40kg Baggage", "Complimentary Meal", "Fast Track"]
  },
  {
    id: "FL-021",
    flightNumber: "QZ-552",
    origin: "DPS",
    originCity: "Bali",
    originAirport: "Ngurah Rai International Airport",
    destination: "KUL",
    destinationCity: "Kuala Lumpur",
    destinationAirport: "Kuala Lumpur International Airport (Terminal 2)",
    daysAhead: 4,
    departureTime: "13:10",
    arrivalTime: "16:15",
    duration: "3h 05m",
    durationMinutes: 185,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 21,
    baseFareBDT: 14200,
    taxBDT: 2400,
    priceBDT: 16600,
    amenities: ["Carry-on 7kg", "Santan Nasi Lemak"]
  },

  // KUL <-> BKK (Kuala Lumpur to Bangkok)
  {
    id: "FL-022",
    flightNumber: "FD-3101",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "BKK",
    destinationCity: "Bangkok",
    destinationAirport: "Don Mueang International Airport (DMK)",
    daysAhead: 1,
    departureTime: "06:45",
    arrivalTime: "08:00",
    duration: "2h 15m",
    durationMinutes: 135,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 35,
    baseFareBDT: 8500,
    taxBDT: 1900,
    priceBDT: 10400,
    amenities: ["Carry-on 7kg", "Morning Coffee Service"]
  },
  {
    id: "FL-023",
    flightNumber: "AK-882",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "BKK",
    destinationCity: "Bangkok",
    destinationAirport: "Don Mueang International Airport (DMK)",
    daysAhead: 1,
    departureTime: "11:55",
    arrivalTime: "13:10",
    duration: "2h 15m",
    durationMinutes: 135,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 27,
    baseFareBDT: 9200,
    taxBDT: 1900,
    priceBDT: 11100,
    amenities: ["Carry-on 7kg", "Hot Meals Available"]
  },
  {
    id: "FL-024",
    flightNumber: "AK-886",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "BKK",
    destinationCity: "Bangkok",
    destinationAirport: "Don Mueang International Airport (DMK)",
    daysAhead: 2,
    departureTime: "18:40",
    arrivalTime: "19:55",
    duration: "2h 15m",
    durationMinutes: 135,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A321neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 19,
    baseFareBDT: 9800,
    taxBDT: 1900,
    priceBDT: 11700,
    amenities: ["Carry-on 7kg", "Quiet Zone Seating"]
  },

  // DAC <-> PEN (Dhaka to Penang via KUL)
  {
    id: "FL-025",
    flightNumber: "AK-512 / AK-6112",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "PEN",
    destinationCity: "Penang",
    destinationAirport: "Penang International Airport",
    daysAhead: 1,
    departureTime: "01:25",
    arrivalTime: "09:50",
    duration: "6h 25m",
    durationMinutes: 385,
    stops: 1,
    stopsText: "1 Stop (KUL 1h 35m)",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 12,
    baseFareBDT: 23800,
    taxBDT: 3400,
    priceBDT: 27200,
    amenities: ["Carry-on 7kg", "Fly-Thru Connection"]
  },
  {
    id: "FL-026",
    flightNumber: "AK-6113 / AK-515",
    origin: "PEN",
    originCity: "Penang",
    originAirport: "Penang International Airport",
    destination: "DAC",
    destinationCity: "Dhaka",
    destinationAirport: "Hazrat Shahjalal Intl Airport",
    daysAhead: 4,
    departureTime: "16:40",
    arrivalTime: "21:35",
    duration: "6h 55m",
    durationMinutes: 415,
    stops: 1,
    stopsText: "1 Stop (KUL 2h 05m)",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 18,
    baseFareBDT: 24200,
    taxBDT: 3400,
    priceBDT: 27600,
    amenities: ["Carry-on 7kg", "Fly-Thru Connection"]
  },

  // KUL <-> HKT (Kuala Lumpur to Phuket)
  {
    id: "FL-027",
    flightNumber: "AK-824",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "HKT",
    destinationCity: "Phuket",
    destinationAirport: "Phuket International Airport",
    daysAhead: 1,
    departureTime: "10:15",
    arrivalTime: "10:40",
    duration: "1h 25m",
    durationMinutes: 85,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 29,
    baseFareBDT: 7200,
    taxBDT: 1700,
    priceBDT: 8900,
    amenities: ["Carry-on 7kg", "Beach Holiday Route"]
  },
  {
    id: "FL-028",
    flightNumber: "AK-828",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "HKT",
    destinationCity: "Phuket",
    destinationAirport: "Phuket International Airport",
    daysAhead: 2,
    departureTime: "17:50",
    arrivalTime: "18:15",
    duration: "1h 25m",
    durationMinutes: 85,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 25,
    baseFareBDT: 7800,
    taxBDT: 1700,
    priceBDT: 9500,
    amenities: ["Carry-on 7kg"]
  },

  // KUL <-> TYO/HND (Kuala Lumpur to Tokyo Haneda)
  {
    id: "FL-029",
    flightNumber: "D7-522",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "TYO",
    destinationCity: "Tokyo",
    destinationAirport: "Haneda Airport (HND)",
    daysAhead: 2,
    departureTime: "14:30",
    arrivalTime: "22:30",
    duration: "7h 00m",
    durationMinutes: 420,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A330-300",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 40,
    baseFareBDT: 32000,
    taxBDT: 4800,
    priceBDT: 36800,
    amenities: ["Carry-on 7kg", "Long Haul Entertainment", "Japanese Bento Pre-order"]
  },
  {
    id: "FL-030",
    flightNumber: "D7-524",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "TYO",
    destinationCity: "Tokyo",
    destinationAirport: "Haneda Airport (HND)",
    daysAhead: 3,
    departureTime: "23:45",
    arrivalTime: "07:45",
    duration: "7h 00m",
    durationMinutes: 420,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A330-300",
    cabinClass: "Premium Flatbed",
    baggageAllowance: "40 kg check-in + 7 kg cabin",
    availableSeats: 5,
    baseFareBDT: 72000,
    taxBDT: 6500,
    priceBDT: 78500,
    amenities: ["Lie-Flat Bed", "40kg Baggage", "Gourmet Dining", "Priority Baggage & Boarding"]
  },

  // KUL <-> ICN (Kuala Lumpur to Seoul Incheon)
  {
    id: "FL-031",
    flightNumber: "D7-504",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "ICN",
    destinationCity: "Seoul",
    destinationAirport: "Incheon International Airport",
    daysAhead: 2,
    departureTime: "01:00",
    arrivalTime: "08:30",
    duration: "6h 30m",
    durationMinutes: 390,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A330-300",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 35,
    baseFareBDT: 29500,
    taxBDT: 4500,
    priceBDT: 34000,
    amenities: ["Carry-on 7kg", "Korean Meal Options", "Comfort Kit"]
  },

  // KUL <-> CGK (Kuala Lumpur to Jakarta)
  {
    id: "FL-032",
    flightNumber: "QZ-201",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "CGK",
    destinationCity: "Jakarta",
    destinationAirport: "Soekarno-Hatta International Airport",
    daysAhead: 1,
    departureTime: "08:30",
    arrivalTime: "09:35",
    duration: "2h 05m",
    durationMinutes: 125,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 42,
    baseFareBDT: 6800,
    taxBDT: 1600,
    priceBDT: 8400,
    amenities: ["Carry-on 7kg", "Quick Business Route"]
  },
  {
    id: "FL-033",
    flightNumber: "QZ-205",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "CGK",
    destinationCity: "Jakarta",
    destinationAirport: "Soekarno-Hatta International Airport",
    daysAhead: 2,
    departureTime: "16:50",
    arrivalTime: "17:55",
    duration: "2h 05m",
    durationMinutes: 125,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 31,
    baseFareBDT: 7200,
    taxBDT: 1600,
    priceBDT: 8800,
    amenities: ["Carry-on 7kg"]
  },

  // DAC <-> CGK (Dhaka to Jakarta via KUL)
  {
    id: "FL-034",
    flightNumber: "AK-512 / QZ-205",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "CGK",
    destinationCity: "Jakarta",
    destinationAirport: "Soekarno-Hatta International Airport",
    daysAhead: 1,
    departureTime: "01:25",
    arrivalTime: "11:45",
    duration: "9h 20m",
    durationMinutes: 560,
    stops: 1,
    stopsText: "1 Stop (KUL 3h 15m)",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 14,
    baseFareBDT: 26000,
    taxBDT: 3700,
    priceBDT: 29700,
    amenities: ["Carry-on 7kg", "Fly-Thru Connection"]
  },

  // DAC <-> DPS (Dhaka to Bali via KUL)
  {
    id: "FL-035",
    flightNumber: "AK-512 / QZ-551",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "DPS",
    destinationCity: "Bali",
    destinationAirport: "Ngurah Rai International Airport",
    daysAhead: 1,
    departureTime: "01:25",
    arrivalTime: "12:25",
    duration: "9h 00m",
    durationMinutes: 540,
    stops: 1,
    stopsText: "1 Stop (KUL 2h 10m)",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 16,
    baseFareBDT: 29500,
    taxBDT: 4200,
    priceBDT: 33700,
    amenities: ["Carry-on 7kg", "Fly-Thru Island Route"]
  },
  {
    id: "FL-036",
    flightNumber: "AK-514 / QZ-555",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "DPS",
    destinationCity: "Bali",
    destinationAirport: "Ngurah Rai International Airport",
    daysAhead: 2,
    departureTime: "12:40",
    arrivalTime: "23:55",
    duration: "9h 15m",
    durationMinutes: 555,
    stops: 1,
    stopsText: "1 Stop (KUL 2h 20m)",
    aircraft: "Airbus A321neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 18,
    baseFareBDT: 30800,
    taxBDT: 4200,
    priceBDT: 35000,
    amenities: ["Carry-on 7kg", "Hot Meal Pre-order"]
  },

  // KUL <-> LGK (Kuala Lumpur to Langkawi Domestic)
  {
    id: "FL-037",
    flightNumber: "AK-6302",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "LGK",
    destinationCity: "Langkawi",
    destinationAirport: "Langkawi International Airport",
    daysAhead: 1,
    departureTime: "08:15",
    arrivalTime: "09:20",
    duration: "1h 05m",
    durationMinutes: 65,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 48,
    baseFareBDT: 3500,
    taxBDT: 900,
    priceBDT: 4400,
    amenities: ["Carry-on 7kg", "Duty-Free Island Shuttle"]
  },
  {
    id: "FL-038",
    flightNumber: "AK-6316",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "LGK",
    destinationCity: "Langkawi",
    destinationAirport: "Langkawi International Airport",
    daysAhead: 2,
    departureTime: "14:40",
    arrivalTime: "15:45",
    duration: "1h 05m",
    durationMinutes: 65,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 35,
    baseFareBDT: 3800,
    taxBDT: 900,
    priceBDT: 4700,
    amenities: ["Carry-on 7kg"]
  },

  // KUL <-> BKI (Kuala Lumpur to Kota Kinabalu)
  {
    id: "FL-039",
    flightNumber: "AK-5104",
    origin: "KUL",
    originCity: "Kuala Lumpur",
    originAirport: "Kuala Lumpur International Airport (Terminal 2)",
    destination: "BKI",
    destinationCity: "Kota Kinabalu",
    destinationAirport: "Kota Kinabalu International Airport",
    daysAhead: 1,
    departureTime: "11:20",
    arrivalTime: "14:00",
    duration: "2h 40m",
    durationMinutes: 160,
    stops: 0,
    stopsText: "Direct",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 30,
    baseFareBDT: 6500,
    taxBDT: 1400,
    priceBDT: 7900,
    amenities: ["Carry-on 7kg", "Borneo Gateway"]
  },

  // DAC <-> HKT (Dhaka to Phuket via BKK or KUL)
  {
    id: "FL-040",
    flightNumber: "FD-181 / FD-3025",
    origin: "DAC",
    originCity: "Dhaka",
    originAirport: "Hazrat Shahjalal Intl Airport",
    destination: "HKT",
    destinationCity: "Phuket",
    destinationAirport: "Phuket International Airport",
    daysAhead: 2,
    departureTime: "02:10",
    arrivalTime: "09:30",
    duration: "6h 20m",
    durationMinutes: 380,
    stops: 1,
    stopsText: "1 Stop (DMK 2h 25m)",
    aircraft: "Airbus A320neo",
    cabinClass: "Economy",
    baggageAllowance: "7 kg cabin bag included",
    availableSeats: 15,
    baseFareBDT: 22800,
    taxBDT: 3400,
    priceBDT: 26200,
    amenities: ["Carry-on 7kg", "Fly-Thru Andaman Route"]
  }
];
